obj-m += note_kref_work.o
obj-m += note_kref_static.o
obj-m += note_kref_object.o
obj-m += note_kref_registry.o
obj-m += note_kref_shutdown.o
obj-m += note_kref_locked.o
obj-m += note_kref_owned_work.o
